# Change these first
owner: touguy # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: TI-Home
    url: https://hanati.co.kr/
  - name: HIT
    url: https://hit.hanati.co.kr/
    __dangerous__insecure: true
  - name: OneQOn
    url: https://oneqon.hanati.co.kr/
    __dangerous__insecure: true
  - name: Trust
    url: https://www.hanatrust.com/
  - name: AAMC
    url: https://hana-aamc.com/
  - name: ASP-Webmail
    url: https://hmail.hanafn.com/
  - name: TI-DHR
    url: https://dhr.hanati.co.kr/
    __dangerous__insecure: true
  - name: TI-ePos
    url: https://tipartner.hanati.co.kr/
    __dangerous__insecure: true
  - name: Grooteogi
    url: https://www.stump.or.kr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**HanaTI-MSP**'s Uptime"
  introMessage: Check Out pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Wiki
      href: https://mwr21.ml/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
